/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPortalScheduleRouteImport } from './routes/_authenticated/portal.schedule'
import { Route as AuthenticatedPortalPerformanceRouteImport } from './routes/_authenticated/portal.performance'
import { Route as AuthenticatedPortalFeesRouteImport } from './routes/_authenticated/portal.fees'
import { Route as AuthenticatedPortalAttendanceRouteImport } from './routes/_authenticated/portal.attendance'
import { Route as AuthenticatedCoachStudentsRouteImport } from './routes/_authenticated/coach.students'
import { Route as AuthenticatedCoachScheduleRouteImport } from './routes/_authenticated/coach.schedule'
import { Route as AuthenticatedCoachPerformanceRouteImport } from './routes/_authenticated/coach.performance'
import { Route as AuthenticatedCoachAttendanceRouteImport } from './routes/_authenticated/coach.attendance'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin.fees'
import { Route as AuthenticatedAdminCoachesRouteImport } from './routes/_authenticated/admin.coaches'
import { Route as AuthenticatedAdminBatchesRouteImport } from './routes/_authenticated/admin.batches'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPortalScheduleRoute =
  AuthenticatedPortalScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPerformanceRoute =
  AuthenticatedPortalPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFeesRoute = AuthenticatedPortalFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalAttendanceRoute =
  AuthenticatedPortalAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedCoachStudentsRoute =
  AuthenticatedCoachStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachScheduleRoute =
  AuthenticatedCoachScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachPerformanceRoute =
  AuthenticatedCoachPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachAttendanceRoute =
  AuthenticatedCoachAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCoachesRoute =
  AuthenticatedAdminCoachesRouteImport.update({
    id: '/coaches',
    path: '/coaches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBatchesRoute =
  AuthenticatedAdminBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/batches': typeof AuthenticatedAdminBatchesRoute
  '/admin/coaches': typeof AuthenticatedAdminCoachesRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coach/attendance': typeof AuthenticatedCoachAttendanceRoute
  '/coach/performance': typeof AuthenticatedCoachPerformanceRoute
  '/coach/schedule': typeof AuthenticatedCoachScheduleRoute
  '/coach/students': typeof AuthenticatedCoachStudentsRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/fees': typeof AuthenticatedPortalFeesRoute
  '/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/portal/schedule': typeof AuthenticatedPortalScheduleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/batches': typeof AuthenticatedAdminBatchesRoute
  '/admin/coaches': typeof AuthenticatedAdminCoachesRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coach/attendance': typeof AuthenticatedCoachAttendanceRoute
  '/coach/performance': typeof AuthenticatedCoachPerformanceRoute
  '/coach/schedule': typeof AuthenticatedCoachScheduleRoute
  '/coach/students': typeof AuthenticatedCoachStudentsRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/fees': typeof AuthenticatedPortalFeesRoute
  '/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/portal/schedule': typeof AuthenticatedPortalScheduleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/batches': typeof AuthenticatedAdminBatchesRoute
  '/_authenticated/admin/coaches': typeof AuthenticatedAdminCoachesRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/coach/attendance': typeof AuthenticatedCoachAttendanceRoute
  '/_authenticated/coach/performance': typeof AuthenticatedCoachPerformanceRoute
  '/_authenticated/coach/schedule': typeof AuthenticatedCoachScheduleRoute
  '/_authenticated/coach/students': typeof AuthenticatedCoachStudentsRoute
  '/_authenticated/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/_authenticated/portal/fees': typeof AuthenticatedPortalFeesRoute
  '/_authenticated/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/_authenticated/portal/schedule': typeof AuthenticatedPortalScheduleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/auth'
    | '/coaches'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/admin'
    | '/coach'
    | '/portal'
    | '/admin/attendance'
    | '/admin/batches'
    | '/admin/coaches'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/users'
    | '/coach/attendance'
    | '/coach/performance'
    | '/coach/schedule'
    | '/coach/students'
    | '/portal/attendance'
    | '/portal/fees'
    | '/portal/performance'
    | '/portal/schedule'
    | '/admin/'
    | '/coach/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/auth'
    | '/coaches'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/admin/attendance'
    | '/admin/batches'
    | '/admin/coaches'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/users'
    | '/coach/attendance'
    | '/coach/performance'
    | '/coach/schedule'
    | '/coach/students'
    | '/portal/attendance'
    | '/portal/fees'
    | '/portal/performance'
    | '/portal/schedule'
    | '/admin'
    | '/coach'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/auth'
    | '/coaches'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/_authenticated/admin'
    | '/_authenticated/coach'
    | '/_authenticated/portal'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/batches'
    | '/_authenticated/admin/coaches'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/users'
    | '/_authenticated/coach/attendance'
    | '/_authenticated/coach/performance'
    | '/_authenticated/coach/schedule'
    | '/_authenticated/coach/students'
    | '/_authenticated/portal/attendance'
    | '/_authenticated/portal/fees'
    | '/_authenticated/portal/performance'
    | '/_authenticated/portal/schedule'
    | '/_authenticated/admin/'
    | '/_authenticated/coach/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AuthRoute: typeof AuthRoute
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/schedule': {
      id: '/_authenticated/portal/schedule'
      path: '/schedule'
      fullPath: '/portal/schedule'
      preLoaderRoute: typeof AuthenticatedPortalScheduleRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/performance': {
      id: '/_authenticated/portal/performance'
      path: '/performance'
      fullPath: '/portal/performance'
      preLoaderRoute: typeof AuthenticatedPortalPerformanceRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/fees': {
      id: '/_authenticated/portal/fees'
      path: '/fees'
      fullPath: '/portal/fees'
      preLoaderRoute: typeof AuthenticatedPortalFeesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/attendance': {
      id: '/_authenticated/portal/attendance'
      path: '/attendance'
      fullPath: '/portal/attendance'
      preLoaderRoute: typeof AuthenticatedPortalAttendanceRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/coach/students': {
      id: '/_authenticated/coach/students'
      path: '/students'
      fullPath: '/coach/students'
      preLoaderRoute: typeof AuthenticatedCoachStudentsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/schedule': {
      id: '/_authenticated/coach/schedule'
      path: '/schedule'
      fullPath: '/coach/schedule'
      preLoaderRoute: typeof AuthenticatedCoachScheduleRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/performance': {
      id: '/_authenticated/coach/performance'
      path: '/performance'
      fullPath: '/coach/performance'
      preLoaderRoute: typeof AuthenticatedCoachPerformanceRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/attendance': {
      id: '/_authenticated/coach/attendance'
      path: '/attendance'
      fullPath: '/coach/attendance'
      preLoaderRoute: typeof AuthenticatedCoachAttendanceRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coaches': {
      id: '/_authenticated/admin/coaches'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AuthenticatedAdminCoachesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/batches': {
      id: '/_authenticated/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AuthenticatedAdminBatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminBatchesRoute: typeof AuthenticatedAdminBatchesRoute
  AuthenticatedAdminCoachesRoute: typeof AuthenticatedAdminCoachesRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminBatchesRoute: AuthenticatedAdminBatchesRoute,
  AuthenticatedAdminCoachesRoute: AuthenticatedAdminCoachesRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachAttendanceRoute: typeof AuthenticatedCoachAttendanceRoute
  AuthenticatedCoachPerformanceRoute: typeof AuthenticatedCoachPerformanceRoute
  AuthenticatedCoachScheduleRoute: typeof AuthenticatedCoachScheduleRoute
  AuthenticatedCoachStudentsRoute: typeof AuthenticatedCoachStudentsRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachAttendanceRoute: AuthenticatedCoachAttendanceRoute,
  AuthenticatedCoachPerformanceRoute: AuthenticatedCoachPerformanceRoute,
  AuthenticatedCoachScheduleRoute: AuthenticatedCoachScheduleRoute,
  AuthenticatedCoachStudentsRoute: AuthenticatedCoachStudentsRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAttendanceRoute: typeof AuthenticatedPortalAttendanceRoute
  AuthenticatedPortalFeesRoute: typeof AuthenticatedPortalFeesRoute
  AuthenticatedPortalPerformanceRoute: typeof AuthenticatedPortalPerformanceRoute
  AuthenticatedPortalScheduleRoute: typeof AuthenticatedPortalScheduleRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAttendanceRoute: AuthenticatedPortalAttendanceRoute,
  AuthenticatedPortalFeesRoute: AuthenticatedPortalFeesRoute,
  AuthenticatedPortalPerformanceRoute: AuthenticatedPortalPerformanceRoute,
  AuthenticatedPortalScheduleRoute: AuthenticatedPortalScheduleRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AuthRoute: AuthRoute,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
